apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xht8m3lka-java-springboot
  janus-idp.io/tekton: xht8m3lka-java-springboot
  backstage.io/kubernetes-id: xht8m3lka-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xht8m3lka-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
